### ISSUE TITLE
[Bug]: Something went wrong An unexpected error occurred. Please try refreshing the page.

### ISSUE THREAD

**Issue by ID95613** [lfnovo/open_notebook#256]
### What did you do when it broke?

After updating the latest version of the Docker single image, the web service cannot render or display correctly.

### How did it break?

<img width="768" height="558" alt="Image" src="https://github.com/user-attachments/assets/ff85917a-0807-4546-8985-886ad3bc1346" />

### Logs or Screenshots

964-bcadb576d37033ef.js:1 TypeError: H.map is not a function
    at F (141-f0a2d6a5ab49280f.js:1:14051)
    at l9 (4bd1b696-9911af18dede28aa.js:1:51106)
    at oT (4bd1b696-9911af18dede28aa.js:1:70690)
    at oW (4bd1b696-9911af18dede28aa.js:1:81790)
    at ib (4bd1b696-9911af18dede28aa.js:1:114389)
    at 4bd1b696-9911af18dede28aa.js:1:114234
    at iv (4bd1b696-9911af18dede28aa.js:1:114242)
    at io (4bd1b696-9911af18dede28aa.js:1:111325)
    at iX (4bd1b696-9911af18dede28aa.js:1:132762)
    at iB (4bd1b696-9911af18dede28aa.js:1:130973)

layout-fe621ab01dcfffdb.js:1 Error caught by boundary: TypeError: H.map is not a function
    at F (141-f0a2d6a5ab49280f.js:1:14051)
    at l9 (4bd1b696-9911af18dede28aa.js:1:51106)
    at oT (4bd1b696-9911af18dede28aa.js:1:70690)
    at oW (4bd1b696-9911af18dede28aa.js:1:81790)
    at ib (4bd1b696-9911af18dede28aa.js:1:114389)
    at 4bd1b696-9911af18dede28aa.js:1:114234
    at iv (4bd1b696-9911af18dede28aa.js:1:114242)
    at io (4bd1b696-9911af18dede28aa.js:1:111325)
    at iX (4bd1b696-9911af18dede28aa.js:1:132762)
    at iB (4bd1b696-9911af18dede28aa.js:1:130973)

### Open Notebook Version

v1-latest-single (Docker)

### Environment

- Server OS: Rokcy linux 10, Docker version 28.5.2
- Browser OS: Windows11
- Browser: Chrome 142.0.7444.60

### Contribution

- [ ] I am a developer and would like to work on fixing this issue (pending maintainer approval)

**Comment by lfnovo** [comment]
Hi.. is this issue still happening to you after upgrading to 1.2.3? If so, can you show us the logs for the docker container?

**Comment by ID95613** [comment]
Hi, this issue did not reappear after  upgrading to 1.2.3.
